import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "@/Components/Nav";
import MiddleNav from "@/Components/MiddleNav/MiddleNav";
import SecondNav from "@/Components/SecondNav/SecondNav";
import Footer from "@/Components/Footer/Footer";
import Home from "./page";
import Products from "./AllProduct/page";




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} `} >
        
        <Nav />
        <MiddleNav />
        <SecondNav />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
